// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF2TQY46O6RKRxbViO5MVvAChwvmAUrVw',
    appId: '1:622884464848:web:a630af8e25b70c24ced6d5',
    messagingSenderId: '622884464848',
    projectId: 'liferpg-aaae1',
    authDomain: 'liferpg-aaae1.firebaseapp.com',
    storageBucket: 'liferpg-aaae1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_SgWzN06aG0wipYQc1jt7iFjwTIH-gvg',
    appId: '1:622884464848:android:33889a5e41cb3f82ced6d5',
    messagingSenderId: '622884464848',
    projectId: 'liferpg-aaae1',
    storageBucket: 'liferpg-aaae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrtAdzJmhNpqg8huZYOVCarZfsJPgtwIw',
    appId: '1:622884464848:ios:c53eb6f7942d0cb1ced6d5',
    messagingSenderId: '622884464848',
    projectId: 'liferpg-aaae1',
    storageBucket: 'liferpg-aaae1.appspot.com',
    iosBundleId: 'com.example.lifeRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrtAdzJmhNpqg8huZYOVCarZfsJPgtwIw',
    appId: '1:622884464848:ios:c53eb6f7942d0cb1ced6d5',
    messagingSenderId: '622884464848',
    projectId: 'liferpg-aaae1',
    storageBucket: 'liferpg-aaae1.appspot.com',
    iosBundleId: 'com.example.lifeRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF2TQY46O6RKRxbViO5MVvAChwvmAUrVw',
    appId: '1:622884464848:web:98828e8dab1894bfced6d5',
    messagingSenderId: '622884464848',
    projectId: 'liferpg-aaae1',
    authDomain: 'liferpg-aaae1.firebaseapp.com',
    storageBucket: 'liferpg-aaae1.appspot.com',
  );
}
